### ISSUE TITLE
looking for an example of using ReadVisdData to read CAN/CAN FD messages。

### ISSUE THREAD

**Issue by windfenggg** [ihedvall/mdflib#108]
Dear ihedvall,

Hello, I am currently able to use your ReadData example to read signals. However, when it comes to reading CAN(FD) messages, I'm not sure how to utilize ReadVisdData. Could you kindly provide an example for reading messages, similar to the ReadData example? Thank you.

Best regards.

```
#include <mdf/mdfreader.h>
#include <mdf/ichannelgroup.h>
#include <mdf/idatagroup.h>

using namespace mdf;

int main() {
    MdfReader reader("c:/mdf/example.mf4");  // Note the file is now open.
    reader.ReadEverythingButData();

    const auto* mdf_file = reader.GetFile(); 
    DataGroupList dg_list;                  
    mdf_file->DataGroups(dg_list);

    for (const auto* dg4 : dg_list) {
      ChannelObserverList subscriber_list;
      const auto cg_list = dg4->ChannelGroups();
      for (const auto* cg4 : cg_list ) {
        const auto cn_list = cg4->Channels();
        for (const auto* cn4 : cn_list) {
          auto sub = CreateChannelObserver(*dg4, *cg4, *cn4);
          subscriber_list.push_back(std::move(sub));
        }
      }
      reader.ReadVisdData(*dg4, , , );    
    }
    reader.Close(); 
}

```

**Comment by ihedvall** [comment]
@windfenggg 
VLSD stands for Variable Length Signal Data and is typically used for string and byte array data. The CAN data message consist of timestamp, CAN ID, length and some data bytes. CAN is always 1-8 data bytes while CAN FD can store up to 64 bytes of data. 

Just to confuse everything, there exist a so-called VLSD channel group (CG). This channel group is used to store the bytes while channel group with the VLSD channel only stores an offset into that VLSD channel groups. The VLSD group cannot have any channels. By this trick, the samples can be appended to the MDF file.

The `ReadData()` function reads in all samples including all the VLSD data bytes, into the primary memory. CAN bus loggers should follow the MDF standard, so there should be a 'CAN_DataFrame' channel group in each measurement.

If you have a large file (> 10GB), the read may  fail due to out-of-memory. Instead of read everything, you need to read the file with some partial read. There exist some `ReadXXX()` functions for doing partial reads.

Instead of `ReadData()` you may call `ReadPartialData()` and add a range of samples. 

The` ReadVLSDData()` is little bit tricky to use. It was made to solve the problem when each sample contains a video stream. These files are large (~100GB). The trick is to set the `ReadVLSDData` property to false on the VLSD channel observer to false. The channel observer will now only read in the offset for each sample. This read is done with the ordinary `ReadData()` function and  is fast. This read are followed by a `ReadVLSDData()` call, with the entire offset list or just a part of the offsets. You should add a callback function that is called for each sample.

As you notice the `ReadVLSDData()` function is not so user friendly and not very useful for small byte arrays as CAN (FD) byte arrays. Another method is to not use channel observers and instead attach an Sample Observer that has an OnSample callback. It's up to you to handle each sample but you can now optimize/filter the read as you want. 

There are some (Google) unit tests that shows the usages (mdflib_test/src/testread.cpp):

- TestRead, TestLargeFile. The `ReadVLSDData()` function (22GB file).
- TestRead, TestPartialRead. This test use the `ReadPartialRead()` function.
- TestRead, TestCssSampleObserver. This test use the sample observer.

Ingemar Hedvall

**Comment by ihedvall** [comment]
@windfenggg 
Some simpler answer. The `ReadData()` function should read in all signal data including the CAN (FD) messages. You can use the `ReadPartialData()`, if you only need to read a part of the samples. 

After the `ReadData()`, the channel observer includes all samples and its data in primary memory. You should scan through the channels and get its data by calling the  `IChannelObserver::GetChannelValue<T>()` function or the `IChannelObserver::GetEngValue<T>()` function. The channel value is a non-scaled value while the engineering value is a scaled value. An external application normally uses the `GetEngValue()` function.

You need to keep some track of what type of data the channel holds. For example `GetEngValue<double>()` will not return any valid value if the data type is a byte array (VLSD). Instead call the `GetEngValue< std::vector<uint8_t> >()` to get a byte array (CAN message byte).

You can start optimizing the read of the file in a second step. For example you may check if the channel group has any samples and if it doesn't have any samples, not subscribing of its channels. 

You can also add a single sample observer instead of a bunch of channel observers. You can inherit or add a callback to the observer. The callback will be called for each channel group and sample. This method reduce the memory requirements and is in theory faster. This method require that you are responsible for the caching of samples so if the channel observers working OK for you, continue to use them.

Ingemar Hedvall

**Comment by windfenggg** [comment]
@ihedvall 
Dear ihedvall,
     Hello, when I use the sample observer to read each CANFD message and print the bytes for debugging, the byte information I get is inconsistent with what CANoe generates. The data field information is all incorrect. Is it because CANFD messages cannot be processed in the same way as CAN messages? I am not sure if you have encountered any type-related issues when reading CANFD messages. Thank you."
Best regards.
![2](https://github.com/user-attachments/assets/a6f2f60d-968d-4fcc-85b7-f390da6bc290)
![1](https://github.com/user-attachments/assets/093b25c6-e08c-4205-ae9e-c14d2403a35c)

**Comment by ihedvall** [comment]
@windfenggg 
Sorry. I have mislead both you and myself. The previous outputs are OK. The CAN_DataFrame byte array is of fixed size. It holds all sub-signal values except the CAN_DataFrame.DataBytes that holds an offset into to the VLSD CG block. Well it is little tricky.

For you in the sample observer OnSample() function, The record ID(1) reports all the CAN frames flags and the timestamp but not the CAN data bytes. The record(2) reports the CAN data bytes.  

The channel observers seems to solve this cross-reference why they gives a simple solution. See also ChannelObserver::OnSample() (channelobserver.cpp). 

Your log file may use some other configuration so we need to figure out how to parse the file.

Ingemar Hedvall

**Comment by windfenggg** [comment]
@ihedvall
     You're too kind, it might be that I didn't express myself clearly. Thank you very much for your work; it can process CAN messages correctly. I'm wondering if CAN FD hasn't been fully supported yet, or if I can't read CAN FD in the same way as CAN messages.I'm very glad to receive your reply. Now, I have checked the CAN messages using the MDF Viewer, and there are no issues. I can also parse the CAN_DataFrame byte by byte. Below is the inspection of the CAN messages.
![1](https://github.com/user-attachments/assets/bc2d2807-e788-44a4-91b5-d12941ac8e21)
    However, when I use the MDF Viewer to inspect CAN FD messages, the CAN_DataFrame and data field bytes appear very strange. It seems like some error has occurred, and the byte information is not being displayed correctly like it is for the CAN messages, as shown below. I have an ASC CAN FD message example file, but the tool to convert the example file to MDF (CANoe) is on an internal network. I'm not sure if you have access to any related tools that can convert ASC to MDF, which might help with troubleshooting the issue. Thank you.
![2](https://github.com/user-attachments/assets/0a300778-e7d5-41b6-91ec-541cf6c20faf)
![3](https://github.com/user-attachments/assets/8929ec55-740a-4139-b3f3-bf72132e25d0)
[test_canfd.zip](https://github.com/user-attachments/files/17975043/test_canfd.zip)

**Comment by ihedvall** [comment]
@windfenggg 

I have several files with MLSD and CG-VLSD data storage but I have no file by some other tool that uses SD storage. I test the MDF SD storage against my own writer, which isn't optimal. It should be the configuration of the CAN_DataFrame.DataBytes channel that controls this. 

I don't have any ASC to MDF converters. Just need a hint in the right direction. I append the CAN SD configuration that my unit test uses.

**Comment by ihedvall** [comment]
@windfenggg 
Forgot to append.
![image](https://github.com/user-attachments/assets/44875051-779b-4710-a02f-f2e3a113addb)

**Comment by windfenggg** [comment]
@ihedvall 
     Thank you very much for your reply. I have converted the file to MF4 using another tool. This is a CANFD MF4 file. Could you please check when you have time to see if the CAN_DataFrame can be retrieved properly from it?
[test_canfd.zip](https://github.com/user-attachments/files/17976795/test_canfd.zip)

**Comment by windfenggg** [comment]
@ihedvall 
  I suspect that the DataBytes of the CANFD message might have been compressed, which is causing the incorrect byte information to be retrieved. The SD view you have might be correct, because there is no DZ block under the DataBytes of a CAN message, but there is one under CANFD.
<img width="569" alt="test" src="https://github.com/user-attachments/assets/3590bbbf-b341-48be-baad-5bd5b8229d9b">

**Comment by windfenggg** [comment]
@ihedvall 
    Thank you so much! It seems that your project is very versatile, and I also appreciate your open-source spirit. I hope you enjoy your lunch! When you have some free time, I would love to learn how you managed to correctly read CANFD messages. 
 Best regards！

**Comment by ihedvall** [comment]
@windfenggg 
Added a unit test for the CAN FD file. Just printed out the first 5 samples.
```
TEST_F(TestRead, TestCanFd) {
  std::string test_file = GetMdfFile(kCanFdFile.data());
  if (test_file.empty()) {
    GTEST_SKIP_("CAN FD file not found");
  }

  MdfReader reader(test_file);
  const bool read_config = reader.ReadEverythingButData();
  ASSERT_TRUE(read_config);

  const MdfFile* mf4_file = reader.GetFile();
  ASSERT_TRUE(mf4_file != nullptr);

  std::vector<IDataGroup*> dg_list;
  mf4_file->DataGroups(dg_list);
  EXPECT_EQ(dg_list.size(), 3);

  for (IDataGroup* data_group : dg_list ) {
    ASSERT_TRUE(data_group != nullptr);

    // Subscribe on all channels
    ChannelObserverList observer_list;
    CreateChannelObserverForDataGroup(*data_group, observer_list);
    EXPECT_FALSE(observer_list.empty());

    const bool read = reader.ReadData(*data_group);
    EXPECT_TRUE(read);

    for (uint64_t sample = 0; sample < 5; ++sample) {
      
      bool valid = false;
      uint16_t channel = 0;
      bool direction = false;
      uint32_t can_id = 0;
      std::vector<uint8_t> data_bytes;

      for (const auto &observer : observer_list) {
        if (observer->Name() == "CAN_DataFrame.BusChannel") {
          valid = observer->GetEngValue(sample, channel);
          EXPECT_TRUE(valid);
        } else if (observer->Name() == "CAN_DataFrame.Dir") {
          valid = observer->GetEngValue(sample, direction);
          EXPECT_TRUE(valid);
        } else if (observer->Name() == "CAN_DataFrame.ID") {
          valid = observer->GetEngValue(sample, can_id);
          EXPECT_TRUE(valid);
        } else if (observer->Name() == "CAN_DataFrame.DataBytes") {
          valid = observer->GetEngValue(sample, data_bytes);
          EXPECT_TRUE(valid);
        }
      }
      if (valid) {
        std::cout << "Sample: " << sample
                  << " Channel: " << channel
                  << " Direction: " << (direction ? "Tx" : "Rx")
                  << " Data: ";
        for (uint8_t data : data_bytes) {
          std::cout << std::hex << std::uppercase << std::setw(2)
                    << std::setfill('0') << static_cast<int>(data) << " ";
        }
        std::cout << std::endl;

      }
    }
```
Output: 
Sample: 0 Channel: 1 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 1 Channel: 1 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 2 Channel: 1 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 3 Channel: 1 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 4 Channel: 1 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 0 Channel: 2 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 1 Channel: 2 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 2 Channel: 2 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 3 Channel: 2 Direction: Rx Data: 12 34 56 78 00 00 00 00 
Sample: 4 Channel: 2 Direction: Rx Data: 12 34 56 78 00 00 00 00

**Comment by windfenggg** [comment]
@ihedvall 
Thank you for your reply. I realized that after creating a channel observer, I can directly retrieve sub-channel information using keywords. I can now also read CANFD messages. Thank you so much!
Best regards!

**Comment by windfenggg** [comment]
@ihedvall 
     I apologize for bothering you again. I’ve found that the direction of the CAN FD messages parsed is always Rx, but in the example MF4 file I sent you earlier, the direction for Channel 1 should be Tx, and for Channel 2, it should be Rx. I suspect it’s a data type issue, but even after changing it from a boolean to an integer, it still doesn’t work. It's strange because the "Dir" field in the MDF observer displays the correct information.
    I also have another question: I can now successfully read CAN FD and LIN messages, but the Ethernet frames do not display any information in the MDF observer. Have you ever verified the parsing of Ethernet frames stored in MF4 files? Looking forward to your response. Thank you.
![1](https://github.com/user-attachments/assets/0e7855ae-6c2f-4104-92ce-eaf144c6b527)

**Comment by ihedvall** [comment]
@windfenggg 
Sorry, my mistake. The direction channel has an enumerate conversion (int->string). The correct way is to fetch the engineering value as a string. The channel value is an integer/boolean. I think I forgotten to print out the CAN ID as well.

Note the subscriber list in the unit test has all channels including the sub-channels. In a real usage application you should only add channels that you need data from. Unused observers just spend CPU time and memory.

I have not tested the LIN, FlexRay, MOST or Ethernet loggers. I'm not connected to any (automation) company that have a lot of log file types. According to the standard, the ETH_Frame.DataBytes sub-channel should holds the data bytes. 

There is no reason that the reader shouldn't parse the Ethernet log files but it always some fix needed. The MdfViewer was intended to use for testing and debugging. It can show configuration and data. If you have some example log file, I can look what's the problem.

Ingemar Hedvall

**Comment by windfenggg** [comment]
@ihedvall 
     Thank you for your response. After changing the direction to the string data type, the display is now correct. I also printed the CAN ID myself, and it is accurate. Reading Ethernet data is also working fine now; it was previously due to my incorrect usage.
       I have another question: I want to customize some CAN messages and save them as an MF4 file, but I couldn't find relevant examples. It seems like unit testing requires a lot of configuration. I set up Google Test, but I couldn't get it to run successfully. Writing seems to be more complex than reading. Could you provide a simple example of writing an MF4 file? It’s also possible that I’m not yet proficient with your mdflib project. I've been working with C++ for less than a year so far, and I look forward to your reply.
   Best regards!

**Comment by ihedvall** [comment]
@windfenggg 
Yes, you are correct that reading of an MDF file is quite easy. Writing of an MDF is more difficult as you need to do the DG/CG/CN/CC configuration. The library do most of the bit stuffing for you. You need some knowledge about the MDF file structure.

However writing a CAN log file is much simpler as there exist an ASAM standard how the file should look like and its channel names. There exist a `CanMessage` class and two support functions. The` CreateBusLogConfiguration()` function creates a DG/CG/CN configuration for you while the `SaveCanMessage()` function saves a CAN message.

The only problem is you needs to add an absolute timestamp (ns since 1970 UTC) to each CAN message. 

I recommend to learn how to use a C++ Unit Test tool as Google Test. Most IDE have support for most test tools. The main idea is to test your code as early as possible. This means that you design testable classes/functions and test these units before they run in the end application. 

Below is a unit test for writing a typical CAN bus logger file. Note that it fills with dummy CAN messages.
```
 path mdf_file(kTestDir);
  mdf_file.append("can_sd_storage.mf4");

  auto writer = MdfFactory::CreateMdfWriter(MdfWriterType::MdfBusLogger);
  writer->Init(mdf_file.string());
  auto* header = writer->Header();
  auto* history = header->CreateFileHistory();
  history->Description("Test data types");
  history->ToolName("MdfWrite");
  history->ToolVendor("ACME Road Runner Company");
  history->ToolVersion("1.0");
  history->UserName("Ingemar Hedvall");

  writer->BusType(MdfBusType::CAN); // Defines the CG/CN names
  writer->StorageType(MdfStorageType::FixedLengthStorage); // Variable length to SD
  writer->MaxLength(8); // No meaning in this type of storage
  EXPECT_TRUE(writer->CreateBusLogConfiguration()); // Creates all DG/CG/CN
  writer->PreTrigTime(0.0);
  writer->CompressData(false);

  auto* last_dg = header->LastDataGroup();
  ASSERT_TRUE(last_dg != nullptr);

  auto* can_data_frame = last_dg->GetChannelGroup("CAN_DataFrame");
  auto* can_remote_frame = last_dg->GetChannelGroup("CAN_RemoteFrame");
  auto* can_error_frame = last_dg->GetChannelGroup("CAN_ErrorFrame");
  auto* can_overload_frame = last_dg->GetChannelGroup("CAN_OverloadFrame");

  ASSERT_TRUE(can_data_frame != nullptr);
  ASSERT_TRUE(can_remote_frame != nullptr);
  ASSERT_TRUE(can_error_frame != nullptr);
  ASSERT_TRUE(can_overload_frame != nullptr);

  writer->InitMeasurement();
  auto tick_time = TimeStampToNs();
  writer->StartMeasurement(tick_time);
  size_t sample;
  for (sample = 0; sample < 10; ++sample) {
      // Assigned some dummy data
    auto value = static_cast<double>(sample) + 0.23;
    std::vector<uint8_t> data;
    data.assign(sample < 8 ? sample + 1 : 8, static_cast<uint8_t>(sample + 1));

    CanMessage msg;
    msg.MessageId(123);
    msg.ExtendedId(true);
    msg.BusChannel(11);
    EXPECT_EQ(msg.BusChannel(), 11);
    msg.DataBytes(data);

      // Add dummy message to all for message types. Not realistic
      // but makes the test simpler.
    writer->SaveCanMessage(*can_data_frame, tick_time, msg);
    writer->SaveCanMessage(*can_remote_frame, tick_time, msg);
    writer->SaveCanMessage(*can_error_frame, tick_time, msg);
    writer->SaveCanMessage(*can_overload_frame, tick_time, msg);
    tick_time += 1'000'000;
  }
  writer->StopMeasurement(tick_time);
  writer->FinalizeMeasurement();

```

**Comment by windfenggg** [comment]
@ihedvall 
          Thank you for your response. I would like to request the addition of two protocols, LIN and Ethernet (ETH). Please feel free to make them compatible at your convenience. I would be honored to assist with module testing and contribute to this open-source project. If needed, you can leave me a message on GitHub directly. Currently, I have tools available to generate related log files for LIN and ETH. While MOST and FlexRay are not supported on my end for now, I do have access to third-party tools to test if MF4 files can be read correctly. Thank you!
      Best regards!

**Comment by ihedvall** [comment]
@windfenggg 
I will add 2  request into the MDF projects.The will show up as issues in GitHub. I have some log files (CSS Electronics) with some LIN messages but I don't have any example log files for the Ethernet messages. If you have some example ETH file that you can send over. It's more for verification.

Leaving messages on GitHub, is not really supported. You must assign a issue or something. LinkedIn is a better for more privacy message. E-mail may also work.

I convert this issue to a discussion.

Best Regards 
Ingemar Hedvall
